export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Innehåller", value: "iLike" as const },
    { label: "Innehåller inte", value: "notILike" as const },
    { label: "Är", value: "eq" as const },
    { label: "Är inte", value: "ne" as const },
    { label: "Är tom", value: "isEmpty" as const },
    { label: "Är inte tom", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "Är", value: "eq" as const },
    { label: "Är inte", value: "ne" as const },
    { label: "Är mindre än", value: "lt" as const },
    { label: "Är mindre än eller lika med", value: "lte" as const },
    { label: "Är större än", value: "gt" as const },
    { label: "Är större än eller lika med", value: "gte" as const },
    { label: "är mellan", value: "isBetween" as const },
    { label: "är tom", value: "isEmpty" as const },
    { label: "är inte tom", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "är", value: "eq" as const },
    { label: "är inte", value: "ne" as const },
    { label: "är före", value: "lt" as const },
    { label: "är efter", value: "gt" as const },
    { label: "är på eller före", value: "lte" as const },
    { label: "är på eller efter", value: "gte" as const },
    { label: "är mellan", value: "isBetween" as const },
    { label: "är relativ till idag", value: "isRelativeToToday" as const },
    { label: "är tom", value: "isEmpty" as const },
    { label: "är inte tom", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "är", value: "eq" as const },
    { label: "är inte", value: "ne" as const },
    { label: "är tom", value: "isEmpty" as const },
    { label: "är inte tom", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "har någon av", value: "inArray" as const },
    { label: "har ingen av", value: "notInArray" as const },
    { label: "är tom", value: "isEmpty" as const },
    { label: "är inte tom", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "är", value: "eq" as const },
    { label: "är inte", value: "ne" as const },
  ],
  sortOrders: [
    { label: "stigande", value: "asc" as const },
    { label: "fallande", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["och", "eller"] as const,
};
